export const START_LOADER = 'START_LOADER';
export const END_LOADER = 'END_LOADER';
export const LOAD_TODOS = 'LOAD_TODOS';
export const UPDATE_PAGE = 'UPDATE_PAGE';
export const START_UPDATE_LOADER = 'START_UPDATE_LOADER';
export const END_UPDATE_LOADER = 'END_UPDATE_LOADER';
export const ADD_TODO = 'ADD_TODO';
export const DELETE_TODO = 'DELETE_TODO';

export default {
  START_LOADER,
  END_LOADER,
  LOAD_TODOS,
  UPDATE_PAGE,
  START_UPDATE_LOADER,
  END_UPDATE_LOADER,
  ADD_TODO,
  DELETE_TODO,
};
